Camera: fix compile error caused by add hwjpeg decoder
Compile error log:
hardware/interfaces/camera/device/3.4/default/include/ext_device_v3_4_impl/ExternalCameraDeviceSession.h:39:10:
fatal error: 'MpiJpegDecoder.h' file not found

hardware/interfaces/camera/device/3.5/default/../../3.4/default/include/ext_device_v3_4_impl/ExternalCameraDeviceSession.h:39:10:
fatal error: 'MpiJpegDecoder.h' file not found

Signed-off-by: Wang Panzhenzhuan <randy.wang@rock-chips.com>
Change-Id: I079956fa6d67f204de5e15342cb5fb9eae842a88